### ISSUE TITLE
Use certificate key ID for the intended purpose

### ISSUE THREAD

**Issue by milliams** [isambard-sc/conch#17]
We are currently abusing the key ID field to store project information. This is not used and is non-conventional. Instead it should store something which identifies the user - probably the email address.

From the specification:
> key id is a free-form text field that is filled in by the CA at the time of signing; the intention is that the contents of this field are used to identify the identity principal in log messages.

**Comment by nnimoyoefoki** [comment]
download

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by milliams** [comment]
This was fixed in 94f6ffe by setting it to the email address.
